### PR TITLE
add date in release notes

### PR DESCRIPTION
**Pull request by shaankhosla**

### CODE REVIEW

**Comment by shaankhosla** [comment]
@MatissJanis Let me know what you think about this

**Comment by MatissJanis** [comment]
The dates are already available in github releases and [here](https://actualbudget.org/blog).

Why would we need to manually add them here too? I must be missing some context.

**Comment by shaankhosla** [comment]
Oh haha I didn't even know we had that there, I was checking the release notes here: https://actualbudget.org/docs/releases and looking for a date.

**Comment by shaankhosla** [comment]
Don't need this

**Pull request closed without merging**
